### ISSUE TITLE
Is usage of  #[serde(flatten)] can be an issue?

### ISSUE THREAD

**Issue by zhiburt** [msrd0/openapi_type#25]
Hi there.
I take this crate really cool integrated in `gotham`.

I am not sure if it's a cause of an issue but here it is/

Having such type causes a panic.

```rust
#[derive(OpenapiType, Deserialize, Serialize)]
struct Responce {
    #[serde(flatten)]
    objects: Vec<Vec<Obj>>,
}
```

```
// thread 'main' panicked at 'Flattening produced an error: Expected object', /home/mzhiburt/.cargo/registry/src/github.com-1ecc6299db9ec823/openapi_type-0.2.3/src/private.rs:76:19
```

Happy 2022

**Comment by msrd0** [comment]
`#[serde(flatten)]` support has been added in #17. However, I have no idea how flatten works on non-map types, so yeah, it currently only supports flatten on fields which type is a map.

**Comment by msrd0** [comment]
To quote the serde website (https://serde.rs/attr-flatten.html):

> It is supported only within structs that have named fields, and the field to which it is applied must be a struct or map type.

So I guess while the error message could be improved, your struct won't work.

**Comment by zhiburt** [comment]
Got it.
Thanks for addressing it.
Have a great one.

**Comment by zhiburt** [comment]
Actual `serde` error

```rust
Err(Error("can only flatten structs and maps (got a sequence)", line: 0, column: 0))
```
